services:
  - type: web
    name: rean-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://rean-web-3.vercel.app
      - key: DATABASE_URL
        value: postgresql://clownrean_user:TM9DtL4kKN1b4MI2ljLdrPcZs4gub81B@dpg-d77ethjuibrs73bv3f40-a/clownrean
      - key: JWT_SECRET
        value: 97e6de89461707d1de85386017a4626c6d315a93da2ccddfc8850dde500dd80f